### ISSUE TITLE
Design team member badge

### ISSUE THREAD

**Issue by ScottKillen** [ExtrabiomesXL/extrabiomes-artwork#1]
We need a team member badge (actually an organization avatar) that is recognizable as ExtrabiomesXL and scales well from 20 x 20 to 140 x 140.

This will be the avatar for the Extrabiomes Organization in github and show as a badge on team member's profiles.

**Comment by Rosethorns** [comment]
Heyo, that would be fun :) but before I start I always like to know if the
client has anything specific in mind ;) so if you have any ideas about what
you would like the badge to have or include please fire away, be it text or
a lack there of, or specific imagery.

**Comment by ScottKillen** [comment]
Like all really good clients, I have absolutely no idea...but will let you know when you don't do what I expect.  :) (Can you tell I have dealt with many a client in my day?!)

In all seriousness, hovering over the badge shows the text "ExtrabiomesXL" so I was thinking maybe pick one of our textures (like one of our flowers, or RedRock) and doing a 140x version...but, I will defer to you as the art director. I give you the final say and you will get no complaints!  :D
