### ISSUE TITLE
3D plants

### ISSUE THREAD

**Issue by ScottKillen** [ExtrabiomesXL/extrabiomes-artwork#2]
I'd like to try rendering plants differently than the norm where it makes sense to do so. Specifically, rather than using the standard render for small cacti as we currently do, I would like to make a model and skin for them and render them in 3 dimensions. I know this is possible, but I have not the ability to create the model or skin. Thoughts?

The idea came when I saw a screenshot from the More Plants Mod, which is not currently forge (or extrabiomes) compatibile. A link to the More Plants Mod is below:

http://www.minecraftforum.net/topic/1281729-

We can do other plants as it make sense to (you might as well start work on modeling the fern tree we discussed as well)

**Comment by Rosethorns** [comment]
This is definately in line with our previous discussions, so I would love to work on something like this.

**Comment by ScottKillen** [comment]
So...I'm not sure the first step...I guess research on what kind of model is required and then begin there?

**Comment by Rosethorns** [comment]
Scott can you talk to Eloraam about her pipeline for her 3d models? apparently she used blender for her new blulectric engine and using a proper 3d program like blender would be perfect for me.

**Comment by ScottKillen** [comment]
Sure. What would you like me to ask?

**Comment by Rosethorns** [comment]
what her pipeline is for the models. but specifically.
Do I need a special plugin to export the model as something minecraft readable?
if yes, what is it? where can I get it?
if no, what format should I export the model as?
Do you (scott) need any special custom render code? or is it all already in forge?
Do I need to prep the model objects in any special way? per object? assign bones e.t.c for example
